
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: JDBC_Learning
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    depends_on:
      - mysql
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
